### PR TITLE
In Mobile screen bg-color is showing in only half of screen

### PR DESCRIPTION
**Pull request by Vishalra-i**
I mobile screen bg-color is showing only in half of screen

### CODE REVIEW

**Comment by Vishalra-i** [comment]
Fix responsive bg color

**Comment by Carbrex** [comment]
You would want that to be min-height, won't you?

**Review by tanpreetjolly — CHANGES_REQUESTED** [review]
Hi, md:h-screen doesn't adds any difference to the UI. I suspect you wanted to add min-h-screen? Can you please add those changes

**Review by Vishalra-i — COMMENTED** [review]
Change to min-h-screen

**Comment by tanpreetjolly** [comment]
@Vishalra-i  There's no need to add md: before min-h-screen, that's the default behaviour. Just add min-h-screen

**Review by tanpreetjolly — CHANGES_REQUESTED** [review]
You can removed the md: before min-h-screen

**Pull request merged**
